# Generated by Django 6.0.7 on 2026-07-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'blank': 'This field may not be blank.', 'null': 'This field may not be null.', 'required': 'This field is required.', 'unique': 'A user with that username already exists.'}, max_length=500, unique=True)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('review_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
